### PR TITLE
 Fix indentation issue of inline javascript

### LINKED ISSUE #307: Bug: Inline js has indentation issues
### Plugin Version

1.17.1

### Prettier Version

2.4.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

14.17.1

### Which operating systems have you used?

- [ ] Linux
- [ ] macOS
- [X] Windows

### Prettier config

```json
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": true,
  "tabWidth": 4,
  "trailingComma": "es5",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "*.pug",
  "parser": "pug"
}
```

### Input

```pug
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
        .then(data => data.json())
        .then(json => {
            console.log(json);
        });
```

### Output or Error

```bash
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
      .then(data => data.json())
      .then(json => {
        console.log(json);
      });
```

### Expected Output

```pug
script(src='javascripts/echarts.js')
script(src='javascripts/jquery-3.6.0.js')
link(href='stylesheets/bootstrap.css', rel='stylesheet')
script(src='javascripts/bootstrap.bundle.js')

#main(style='width: 100%; height: 1000px')
script.
    var chartDom = document.getElementById("main");
    var myChart = echarts.init(chartDom, null, { renderer: "canvas" });
    let option;
    fetch("data/chResults.json")
        .then(data => data.json())
        .then(json => {
            console.log(json);
        });
```

### Additional Context

The difference between quotation is acceptable, but the difference between indentation seriously affects programming

### PR DESCRIPTION
**Pull request by Dradows**
closes #307

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -187,7 +187,7 @@ export class PugPrinter {
 	/* eslint-disable @typescript-eslint/indent */
 	private readonly codeInterpolationOptions: Pick<
 		RequiredOptions,
-		'singleQuote' | 'bracketSpacing' | 'arrowParens' | 'printWidth' | 'endOfLine' | 'useTabs' | 'bracketSameLine'
+		'singleQuote' | 'bracketSpacing' | 'arrowParens' | 'printWidth' | 'endOfLine' | 'useTabs' | 'tabWidth' | 'bracketSameLine'
```
Comment (Shinigami92) [inline src/printer.ts:190]: I think you just want to run `pnpm run format`
