### PR TITLE
Handle non-JS script content improvements

### LINKED ISSUE #244: Bug: Can't handle non-JS script content
## Info

| Tool     | Version |
| -------- | ------- |
| Plugin   | v1.15.3 |
| Prettier | v2.3.2  |

## Prettier config

`default`

## Input

```pug
doctype html
html
	head
		script(type='application/ld+json').
			{
				"@context": "http://schema.org",
				"@type": "Website",
				"name": "Example",
				"headline": "Example of problem",
				"url": "https://example.com/"
			}

	body
		div Hello World
```

## Output or Error

```bash
test.pugSyntaxError: Unexpected token (2:12)
  1 | {
> 2 |   "@context": "http://schema.org",
    |             ^
  3 |   "@type": "Website",
  4 |   "name": "Example",
  5 |   "headline": "Example of problem",
    at ir (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:7277)
    at En (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:66392)
    at Object.parse (/home/jason/temp/pug-problem/node_modules/prettier/parser-babel.js:22:332006)
    at Object.parse$a [as parse] (/home/jason/temp/pug-problem/node_modules/prettier/index.js:13684:19)
    at coreFormat (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15215:16)
    at formatWithCursor$1 (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15455:14)
    at /home/jason/temp/pug-problem/node_modules/prettier/index.js:60228:12
    at Object.format (/home/jason/temp/pug-problem/node_modules/prettier/index.js:60248:12)
    at PugPrinter.start-pipeless-text (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:1000:41)
    at PugPrinter.build (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:100:54) {
  loc: { start: { line: 2, column: 12 } },
  codeFrame: '\u001b[0m \u001b[90m 1 |\u001b[39m {\u001b[0m\n' +
    '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 2 |\u001b[39m \t\u001b[32m"@context"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"http://schema.org"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m   |\u001b[39m \t          \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 3 |\u001b[39m \t\u001b[32m"@type"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Website"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 4 |\u001b[39m \t\u001b[32m"name"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Example"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 5 |\u001b[39m \t\u001b[32m"headline"\u001b[39m\u001b[33m:\u001b[39m \u001b[32m"Example of problem"\u001b[39m\u001b[33m,\u001b[39m\u001b[0m'
}
[error] test.pug: Error: SyntaxError: Unexpected token (2:12)
[error]   1 | {
[error] > 2 |   "@context": "http://schema.org",
[error]     |             ^
[error]   3 |   "@type": "Website",
[error]   4 |   "name": "Example",
[error]   5 |   "headline": "Example of problem",
[error]     at PugPrinter.build (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/printer.js:106:23)
[error]     at Object.print (/home/jason/temp/pug-problem/node_modules/@prettier/plugin-pug/dist/index.js:66:40)
[error]     at callPluginPrintFunction (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14958:21)
[error]     at mainPrintInternal (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14896:17)
[error]     at mainPrint (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14878:14)
[error]     at printAstToDoc (/home/jason/temp/pug-problem/node_modules/prettier/index.js:14865:13)
[error]     at coreFormat (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15226:15)
[error]     at formatWithCursor$1 (/home/jason/temp/pug-problem/node_modules/prettier/index.js:15455:14)
[error]     at Object.formatWithCursor (/home/jason/temp/pug-problem/node_modules/prettier/index.js:60228:12)
[error]     at format$1 (/home/jason/temp/pug-problem/node_modules/prettier/bin-prettier.js:16827:21)
```

## Expected Output

```pug
doctype html
html
	head
		script(type='application/ld+json').
			{
				"@context": "http://schema.org",
				"@type": "Website",
				"name": "Example",
				"headline": "Example of problem",
				"url": "https://example.com/"
			}

	body
		div Hello World
```

## Additional Context

I am assuming that the plugin assumes all scripts are JS, but this is annoying when you're not putting JS in a script tag. It can't be fixed with a `//- prettier-ignore` either, as it'll reformat the child content.

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #244

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -1295,12 +1295,27 @@ export class PugPrinter {
 
 		if (this.previousToken?.type === 'dot') {
 			const lastTagToken: TagToken | undefined = previousTagToken(this.tokens, this.currentIndex);
+			let typeAttributeToken: AttributeToken | undefined;
+			if (lastTagToken != null) {
+				const tokens: Token[] = this.tokens.slice(this.tokens.indexOf(lastTagToken) + 1, this.currentIndex - 1);
+				typeAttributeToken = tokens.find((token) => token.type === 'attribute' && token.name === 'type') as
```
Comment (Shinigami92) [inline src/printer.ts:1301]: @ST-DDT Do you know some optimizations for this part?
_Maybe we can have a call about this in the next few days_ :slightly_smiling_face:

File: src/printer.ts [hunk 2]
```diff
@@ -1295,12 +1295,27 @@ export class PugPrinter {
...
-					parser = 'babel';
+				case 'script': {
+					const knownJSTypeValues: string[] = [
+						"'text/javascript'",
+						"'application/javascript'",
+						"'application/ecmascript'"
+					];
+					if (typeAttributeToken == null || knownJSTypeValues.includes(typeAttributeToken.val as string)) {
+						parser = 'babel';
+					}
```
Comment (Shinigami92) [inline src/printer.ts:1316]: @OiYouYeahYou Do you think this is sufficient?
Also I could add `'application/ld-json'` and apply a json formatter.
But I don't know all possible json memetypes :thinking:
Also it would remove some unnecessary quotes and format tabs to spaces if it configured this way. IMO this could be a good thing.

File: tests/issues/issue-244/formatted.pug [hunk 3]
```diff
@@ -0,0 +1,14 @@
+doctype html
+html
+  head
+    script(type="application/ld+json").
+      {
+      	"@context": "http://schema.org",
+      	"@type": "Website",
+      	"name": "Example",
+      	"headline": "Example of problem",
+      	"url": "https://example.com/"
```
Comment (Shinigami92) [inline tests/issues/issue-244/formatted.pug:10]: @OiYouYeahYou I'm talking about this tabs to spaces

File: src/printer.ts (hunk 2 above)
Comment (ST-DDT) [reply src/printer.ts:1316]: I would replace the array with a map `type` -> `parser` that can be extended overwritten by the config.
````js
{
default: "babel",
"application/json": "babel",
"application/java": "checkstyle",...
}
````
That way you only have to care about the well known ones and the user is still able to use their exotic ones.

Comment (ST-DDT) [reply src/printer.ts:1316]: Maybe with an explicit `none` to disable formatting for the element.

Comment (Shinigami92) [reply src/printer.ts]: @OiYouYeahYou nevermind, @ST-DDT hinted me to an improved solution and as it now uses the json parser instead of json in js it also preserve the quotes due to json keys are always quoted
Haven't thought about this yesterday :slightly_smiling_face:

File: src/printer.ts [hunk 4]
```diff
@@ -1295,12 +1295,33 @@ export class PugPrinter {
...
+					const knownJSTypeValues: Record<string, BuiltInParserName> = {
+						// js
+						"'text/javascript'": 'babel',
+						"'application/javascript'": 'babel',
+						"'application/ecmascript'": 'babel',
+						// json
+						"'application/json'": 'json',
+						"'application/ld+json'": 'json'
+					};
+					parser = knownJSTypeValues[typeAttributeToken.val as string];
```
Comment (Shinigami92) [inline src/printer.ts:1322]: Maybe I will move this to utils :thinking:  
That way I can also only create the _mimetype registry_ once

Comment (ST-DDT) [reply src/printer.ts:1322]: I would also strip the quotes in case someone wishes to use double quotes.

Comment (Shinigami92) [reply src/printer.ts:1322]: You are absolutely right :eyes: 
Haven't thought about this :sweat_smile:

File: src/utils/common.ts [hunk 5]
```diff
@@ -54,7 +54,7 @@ export function previousNormalAttributeToken(tokens: ReadonlyArray<Token>, index
 export function previousTypeAttributeToken(tokens: ReadonlyArray<Token>, index: number): AttributeToken | undefined {
 	for (let i: number = index - 1; i > 0; i--) {
 		const token: Token | undefined = tokens[i];
-		if (!token || token.type === 'start-attributes') {
+		if (!token || token.type === 'start-attributes' || token.type === 'tag') {
```
Comment (Shinigami92) [inline src/utils/common.ts:57]: @OiYouYeahYou Just want to let you know that I needed to add a check for a tag token here, cause this could potentially a case:

```pug
div(type="application/json")
script.
  const notJson = true;
```

Also I see pros and cons for the reverse iteration of the tokens :thinking: 
So currently the last type attribute is taken, but I don't know if this is wanted behavior :thinking: 
What do you think?

File: src/printer.ts [hunk 6]
```diff
@@ -1393,7 +1393,10 @@ export class PugPrinter {
 				// Preserve newline
 				tok = this.tokens[index - 1];
 				if (tok?.type === 'text' && tok.val === '') {
-					result += `\n${this.indentString.repeat(this.indentLevel)}`;
+					result += '\n';
+				}
+				if (this.tokens[index + 1]?.type !== 'outdent') {
+					result += this.indentString.repeat(this.indentLevel);
```
Comment (Shinigami92) [inline src/printer.ts:1399]: @OiYouYeahYou This is also needed to remove some whitespaces after a piped script tag on a blank line

File: src/utils/script-mime-types.ts [hunk 7]
```diff
@@ -10,15 +10,15 @@ const wrappingQuotesRe: RegExp = /(^("|'|`))|(("|'|`)$)/g;
...
 //       will be handled separately
-const scriptTypeToParserMap: Map<string, BuiltInParserName> = new Map([
-	['application/ecmascript', 'babel'],
-	['application/javascript', 'babel'],
-	['application/json', 'json'],
-	['text/ecmascript', 'babel'],
-	['text/javascript', 'babel'],
-	['text/markdown', 'markdown'],
-	['text/typescript', 'typescript']
-]);
```
Comment (Shinigami92) [inline src/utils/script-mime-types.ts:21]: @OiYouYeahYou Should we also add `'module'` explicitly? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html

**Review by ST-DDT — APPROVED** [review]

File: src/utils/script-mime-types.ts [hunk 8]
```diff
@@ -50,5 +50,5 @@ export function getScriptParserName(typeAttrToken?: AttributeToken): BuiltInPars
 		return suffixExec[1] as unknown as 'json' | 'yaml';
 	}
 
-	return scriptTypeToParserMap.get(type);
+	return scriptTypeToParserMap[type];
```
Comment (OiYouYeahYou) [inline src/utils/script-mime-types.ts:53]: The reason I use maps is because this can return unexpected values. If for whatever reason `type` is equal to something on the `Object.prototype`, it won't return a string.

So if you do use the Record approach, I'd recommend using `Object.prototype.hasOwnProperty`:
```js
if (record.hasOwnProperty(type)) {
    return record[type]
}
```

File: src/utils/script-mime-types.ts [hunk 9]
```diff
@@ -1,5 +1,5 @@
-import { BuiltInParserName } from 'prettier';
-import { AttributeToken } from 'pug-lexer';
+import type { BuiltInParserName } from 'prettier';
+import type { AttributeToken } from 'pug-lexer';
```
Comment (OiYouYeahYou) [inline src/utils/script-mime-types.ts:2]: TIL you can do this - thank you

File: src/utils/script-mime-types.ts (hunk 8 above)
Comment (Shinigami92) [reply src/utils/script-mime-types.ts:53]: Oh my god 👀 
I didn't know that! Thanks for teaching me this. That completely changes my view of the use of Map. Until now I've always tried to avoid them as much as possible, because they actually only brought overhead. But here it actually makes sense.
