### PR TITLE
Preserve backticks for class and id attributes

### LINKED ISSUE #261: Bug: Can't preserve backticks
## Info

| Tool      | Version  |
| --------- | -------- |
| Plugin    | v1.16.0  |
| Prettier  | v2.3.2   |
| Framework | none     |
| Node      | v14.16.1 |
| OS        | linux    |

## Prettier config

```json
{
    "arrowParens": "avoid",
    "bracketSpacing": true,
    "htmlWhitespaceSensitivity": "css",
    "insertPragma": false,
    "jsxBracketSameLine": false,
    "jsxSingleQuote": true,
    "printWidth": 120,
    "proseWrap": "preserve",
    "quoteProps": "as-needed",
    "requirePragma": false,
    "semi": true,
    "singleQuote": true,
    "tabWidth": 2,
    "trailingComma": "all",
    "useTabs": false,
    "vueIndentScriptAndStyle": false,
    "endOfLine": "lf",
    "pugSingleQuote": false,
    "pugTabWidth": 4,
    "pugEmptyAttributes": "none"
}

```

## Input

> Below backtick usage is converted to double quotes

```pug
img(src=post.img, class=`${roundness}`)
```

## Output or Error

> backtick converted to double quotes so generated HTML have below incorrect class

```html
<img class="${roundness}" src="https://picsum.photos/400/225">
```

## Expected Output

```html
<img class="rounded-lg" src="https://picsum.photos/400/225">
```

## Additional Context

`roundness` is a global variable:

```bash
pug -O "{roundness: 'rounded-lg'}" -w ./index.pug -o . -P
```

So, How can I make this plugin preserve backtick when I save in vs code?

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #261

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -787,7 +788,7 @@ export class PugPrinter {
 		formatEmptyAttribute(token, this.options.pugEmptyAttributes, this.options.pugEmptyAttributesForceQuotes);
 
 		if (typeof token.val === 'string') {
-			if (isQuoted(token.val)) {
+			if (isQuoted(token.val) && !isBacktickQuoted(token.val)) {
```
Comment (Shinigami92) [inline src/printer.ts:791]: @Yann-prak Do you think this is a good idea?
Do you think there is a better way?
