### PR TITLE
Fix trailing indentations after pipeless text

### LINKED ISSUE #278: Bug: style element indents
## Info

| Tool      | Version                 |
| --------- | ----------------------- |
| Plugin    | v1.16.2                  |
| Prettier  | v2.3.1                  |
| Framework | none |
| Node      | v14.17.3                  |
| OS        | mac           |

## Prettier config

```yml
tabWidth: 4
bracketSpacing: true
printWidth: 120
singleQuote: true
trailingComma: none
useTabs: true
semi: true
arrowParens: avoid
endOfLine: auto
overrides:
  - files: '*.pug'
    options:
      pugSingleQuote: 'true'
      pugAttributeSeparator: always
      pugClosingBracketPosition: new-line
      pugWrapAttributesThreshold: 1
      pugExplicitDiv: false
      pugClassNotation: literal
      pugEmptyAttributes: none
      pugSortAttributes: asc
      pugSortAttributesBeginning:
        - id
        - class
        - src
        - href
        - type
        - width
        - height
        - alt
        - aria-
        - data-
```

## Input

```pug
// one
html
	head
		style(type='text/css').
			.card-body {
				background-color: white;
				color: #2c2c2c;
				font-size: 0.9rem;
				padding: 25px;
			}		// additional indent
		block styles
	body

// two
block content
	style(type='text/css').
		.entry__name {
			text-align: center;
			margin: 0 0 60px;
		}	// additional indent
	h1.entry__title
		b Credentialing Packet

// three
block content
	style(type='text/css').
		.entry__generalinfo-list {
			display: -webkit-box;
			display: -webkit-flex;
			display: flex;
			-webkit-flex-wrap: wrap;
			flex-wrap: wrap;
		}
	// additional indent
	h2.title General Information
```

## Expected Output

```pug
// one
html
	head
		style(type='text/css').
			.card-body {
				background-color: white;
				color: #2c2c2c;
				font-size: 0.9rem;
				padding: 25px;
			}
		block styles
	body

// two
block content
	style(type='text/css').
		.entry__name {
			text-align: center;
			margin: 0 0 60px;
		}
	h1.entry__title
		b Credentialing Packet

// three
block content
	style(type='text/css').
		.entry__generalinfo-list {
			display: -webkit-box;
			display: -webkit-flex;
			display: flex;
			-webkit-flex-wrap: wrap;
			flex-wrap: wrap;
		}

	h2.title General Information
```

## Additional Context

Hi there!

Several problems with indents in the `style` element.

I hope this helps make your package even better. Thank you 🙏

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #278

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -1406,9 +1406,10 @@ export class PugPrinter {
 				tok = this.tokens[index - 1];
 				if (tok?.type === 'text' && tok.val === '') {
 					result += '\n';
-				}
-				if (this.tokens[index + 1]?.type !== 'outdent') {
-					result += this.indentString.repeat(this.indentLevel);
+					const nextToken: Token | undefined = this.tokens[index + 1];
+					if (nextToken?.type !== 'outdent' && nextToken?.type !== 'newline') {
+						result += this.indentString.repeat(this.indentLevel);
+					}
```
Comment (ST-DDT) [inline src/printer.ts:1412]: In which scenario is this block actually required? Maybe use a positive list instead of block list?

Comment (Shinigami92) [reply src/printer.ts]: Seems we can just remove it :eyes: 
At least all tests passes :smile:

**Review by ST-DDT — APPROVED** [review]
