### PR TITLE
Fix trailing whitespace after tag

### LINKED ISSUE #425: Bug: Trailing whitespace in tags is not trimmed
### Plugin Version

v2.3.0

### Prettier Version

v2.8.1

### Which frameworks are affected?

- [X] none
- [ ] vue
- [ ] angular
- [ ] svelte

### Node Version

v16.17.0

### Which operating systems have you used?

- [ ] Linux
- [X] macOS
- [ ] Windows

### Prettier config

```json
{

}
```

### Input

```pug
html
  body
    p 
      a Link
```

### Output or Error

```bash
html
  body
    p 
      |
      a Link
```

### Expected Output

```pug
html
  body
    p
      a Link
```

### Additional Context

Note the mixed whitespace immediately following the `p` element.
The major problem with this bug is that running prettier on this output yields an even different result (more pipes).

### PR DESCRIPTION
**Pull request by Shinigami92**
closes #425

### CODE REVIEW

File: src/printer.ts [hunk 1]
```diff
@@ -1567,6 +1567,10 @@ export class PugPrinter {
       val = ` ${val}`;
     }
 
+    if (val === ' ' && this.nextToken?.type === 'indent') {
+      val = val.trimEnd();
+    }
```
Comment (Shinigami92) [inline src/printer.ts:1572]: Awaiting to find a time slot with @ST-DDT to discuss if this is the optimal solution

Comment (Shinigami92) [reply src/printer.ts]: Thx to @ST-DDT we found that the prev applied fix was even incorrect :pray: 
Now it does what the actual expected result should be + it's optimized

**Review by ST-DDT — APPROVED** [review]
